name: CMake

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        # preset: [ninja-debug, ninja-release]
        preset: [ninja-debug]

    runs-on: ${{ matrix.os }}

    steps:
    - name: List Xcode installations
      if: matrix.os == 'macos-14'
      run: sudo ls -1 /Applications | grep "Xcode"

    - name: Select Xcode 16.2
      if: matrix.os == 'macos-14'
      run: sudo xcode-select -s /Applications/Xcode_16.2.0.app/Contents/Developer

    - name: Install JUCE dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
          sudo apt update
          sudo apt install libasound2-dev libjack-jackd2-dev \
               ladspa-sdk \
               libcurl4-openssl-dev  \
               libfreetype-dev libfontconfig1-dev \
               libx11-dev libxcomposite-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev \
               libwebkit2gtk-4.1-dev \
               libglu1-mesa-dev mesa-common-dev

    - uses: ilammy/msvc-dev-cmd@v1 # use MSVC on Windows not minGW

    - name: Install ninja-build tool
      if: matrix.os != 'windows-latest'
      uses: seanmiddleditch/gha-setup-ninja@v5

    - name: Cache ninja-build
      if: matrix.os != 'windows-latest'
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-ninja-build
        path: |
          ${GITHUB_WORKSPACE}/ninja-build

    - uses: actions/checkout@v4

    - name: Cache dependencies
      id: cache-libs
      uses: actions/cache@v4
      with:
        path: complete/libs
        key: ${{ runner.os }}-libs-${{ hashFiles('complete/CMakeLists.txt') }}-${{ hashFiles('complete/test/CMakeLists.txt') }}

    - name: Configure CMake
      if: matrix.os != 'windows-latest'
      working-directory: ${{ github.workspace }}/complete
      run: cmake --preset ${{ matrix.preset }}

    - name: Build
      if: matrix.os != 'windows-latest'
      working-directory: ${{ github.workspace }}/complete
      run: cmake --build --preset ${{ matrix.preset }}

    - name: Test
      if: matrix.os != 'windows-latest'
      working-directory: ${{github.workspace}}/complete
      run: ctest --preset ${{ matrix.preset }}

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      working-directory: ${{ github.workspace }}/complete
      run: cmake --preset vs

    - name: Build Debug (Windows)
      if: matrix.os == 'windows-latest'
      working-directory: ${{ github.workspace }}/complete
      run: cmake --build --preset vs --config Debug

    - name: Build Release (Windows)
      if: matrix.os == 'windows-latest'
      working-directory: ${{ github.workspace }}/complete
      run: cmake --build --preset vs --config Debug

    - name: Test Debug (Windows)
      if: matrix.os == 'windows-latest'
      working-directory: ${{ github.workspace }}/complete
      run: ctest --preset vs -C Debug

    - name: Test Release (Windows)
      if: matrix.os == 'windows-latest'
      working-directory: ${{ github.workspace }}/complete
      run: ctest --preset vs -C Release


